#arch:
#  - arm64

#env:
#  - IMGNAME=mitin20/discordbot:latest

#services:
#  - docker

#before_install:
#  - docker image build -t ${IMGNAME} .

#script:
#TravisCI seems to be coming in on undocumented IP addresses.
#  - dig +short myip.opendns.com @resolver1.opendns.com


#after_success:
#  - docker login -u ${DHUB_USERNAME} -p ${DHUB_PASS}
#  - docker push $(IMGNAME)


dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DHUB_PASS" | docker login -u "$DHUB_USERNAME" --password-stdin
      - docker build -t discordbot .
      - docker images
      - docker tag discordbot $DOCKER_USERNAME/discordbot
      - docker push $DOCKER_USERNAME/discordbot
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/discordbot cat hello.txt
    - script: docker run --rm $DOCKER_USERNAME/discordbot cat hello.txt
