arch:
  - arm64

env:
  - IMGNAME=mitin20/discordbot:latest

services:
  - docker

before_install:
  - docker image build -t ${IMGNAME} .

script:
#TravisCI seems to be coming in on undocumented IP addresses.
  - dig +short myip.opendns.com @resolver1.opendns.com


after_success:
  - docker login -u ${DHUB_USERNAME} -p ${DHUB_PASS}
  - docker push $(IMGNAME)